### ISSUE TITLE
Binomial overflow

### ISSUE THREAD

**Issue by ArrogantGao** [dawbarton/BarycentricInterpolation.jl#7]
Hi, I found that the binomial function in the package simply use Int64 as input type, which make it easily overflow, for example
```julia
julia> using BarycentricInterpolation

julia> p = Equispaced{100}()
ERROR: OverflowError: binomial(100, 18) overflows
Stacktrace:
  [1] binomial(n::Int64, k::Int64)
    @ Base ./intfuncs.jl:1114
  [2] _weight(poly::Type{Equispaced{100, Float64}}, j::Int64)
    @ BarycentricInterpolation ~/.julia/packages/BarycentricInterpolation/rdL9k/src/BarycentricInterpolation.jl:73
  [3] (::BarycentricInterpolation.var"#1#2"{DataType})(j::Int64)
    @ BarycentricInterpolation ./none:0
  [4] iterate
    @ Base ./generator.jl:47 [inlined]
  [5] collect_to!(dest::Vector{…}, itr::Base.Generator{…}, offs::Int64, st::Int64)
    @ Base ./array.jl:890
  [6] collect_to_with_first!
    @ BarycentricInterpolation ./array.jl:868 [inlined]
  [7] collect
    @ BarycentricInterpolation ./array.jl:842 [inlined]
  [8] weights
    @ BarycentricInterpolation ~/.julia/packages/BarycentricInterpolation/rdL9k/src/BarycentricInterpolation.jl:70 [inlined]
  [9] Equispaced{100, Float64}(start::Float64, stop::Float64)
    @ BarycentricInterpolation ~/.julia/packages/BarycentricInterpolation/rdL9k/src/BarycentricInterpolation.jl:34
 [10] Equispaced
    @ BarycentricInterpolation ~/.julia/packages/BarycentricInterpolation/rdL9k/src/BarycentricInterpolation.jl:39 [inlined]
 [11] (Equispaced{100})()
    @ BarycentricInterpolation ~/.julia/packages/BarycentricInterpolation/rdL9k/src/BarycentricInterpolation.jl:39
 [12] top-level scope
    @ REPL[4]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

I change the `_weight` function in the following way in my fork
```Julia
@inline _weight(poly::Type{<: Equispaced{N, T}}, j::Integer) where {N, T} = T((2*xor(isodd(N), iseven(j))-1)*binomial(big(N), j))
```
So that the code can work
```Julia
julia> using BarycentricInterpolation

julia> p = Equispaced{100}()
Equispaced{100, Float64}(0.0, 1.0, [-1.0, -0.98, -0.96, -0.94, -0.92, -0.9, -0.88, -0.86, -0.84, -0.82  …  0.82, 0.84, 0.86, 0.88, 0.9, 0.92, 0.94, 0.96, 0.98, 1.0], [1.0, -100.0, 4950.0, -161700.0, 3.921225e6, -7.528752e7, 1.1920524e9, -1.60075608e10, 1.860878943e11, -1.9022318084e12  …  -1.9022318084e12, 1.860878943e11, -1.60075608e10, 1.1920524e9, -7.528752e7, 3.921225e6, -161700.0, 4950.0, -100.0, 1.0])
```

Is there some better way?

**Comment by dawbarton** [comment]
Equispaced representation points are known to be numerically unstable for high values of N, which is why I didn't worry about the overflow. If you look at the Barycentric weights computed, they have a very large numerical range - up to 1e12 in just the numerical values I can see in the example you give (and it might go higher in the hidden digits!). This is going to very strongly restrict the computation you can do since it is at the limit of double precision arithmetic and you will suffer a significant accuracy loss, which means the benefit of using a large value for N will be completely lost. 

If you want high accuracy, Chebyshev polynomials are much better (see, for example, the book by Trefethen on Spectral Methods in Matlab). They have a non-uniform distribution of points, which can be annoying. If you really do want equi-spaced points, you should use a piecewise polynomial instead and restrict the polynomial order to between 3-8.

**Comment by ArrogantGao** [comment]
Thank you very much, I found there are indeed some accuracy error when I use large $N$.
Actually I am trying to use `Julia` instead of chebfun in Matlab, but it seems that it is not that easy, I will see is there some other way.

**Comment by dawbarton** [comment]
Have you tried [ApproxFun.jl](https://github.com/JuliaApproximation/ApproxFun.jl) which is similar in spirit to ChebFun?

**Comment by ArrogantGao** [comment]
Its performance is not as good as chebfun. For example, `Chebfun` used the adaptive Floater-Hormann scheme for interpolation but `Approxfun.jl` did not.
